package aksw.org.sdw.importer.avro.annotations.maps;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class Disaster {

    public static final Map<String, String> mappings;
    static {
        Map<String, String> map = new HashMap<String, String>();
        map.put("earthquake","http://corp.dbpedia.org/ontology/disaster/Earthquake");
        map.put("landslide","http://corp.dbpedia.org/ontology/disaster/Landslide");
        map.put("mudslide","http://corp.dbpedia.org/ontology/disaster/Mudslide");
        map.put("rockfall","http://corp.dbpedia.org/ontology/disaster/Rockfall");
        map.put("subsidence","http://corp.dbpedia.org/ontology/disaster/Subsidence");
        map.put("tsunami","http://corp.dbpedia.org/ontology/disaster/Tsunami");
        map.put("tidal wave","http://corp.dbpedia.org/ontology/disaster/TidalWave");
        map.put("storm surge","http://corp.dbpedia.org/ontology/disaster/StormSurge");
        map.put("coastal flood","http://corp.dbpedia.org/ontology/disaster/CoastalFlood");
        map.put("glacier lake outburst flood","http://corp.dbpedia.org/ontology/disaster/GlacierLakeOutburstFlood");
        map.put("Jökulhlaup","http://corp.dbpedia.org/ontology/disaster/Jökulhlaup");
        map.put("volcanic activity","http://corp.dbpedia.org/ontology/disaster/VolcanicActivity");
        map.put("volcanic eruption","http://corp.dbpedia.org/ontology/disaster/VolcanicEruption");
        map.put("volcanic ash landslide","http://corp.dbpedia.org/ontology/disaster/VolcanicAshLandslide");
        map.put("Lahar","http://corp.dbpedia.org/ontology/disaster/Lahar");
        map.put("lava flow","http://corp.dbpedia.org/ontology/disaster/LavaFlow");
        map.put("debris flow","http://corp.dbpedia.org/ontology/disaster/DebrisFlow");
        map.put("glowing avalanche","http://corp.dbpedia.org/ontology/disaster/GlowingAvalanche");
        map.put("pyroclastic flow","http://corp.dbpedia.org/ontology/disaster/PyroclasticFlow");
        map.put("eruption","http://corp.dbpedia.org/ontology/disaster/Eruption");
        map.put("avalanche","http://corp.dbpedia.org/ontology/disaster/Avalanche");
        map.put("snow avalanche","http://corp.dbpedia.org/ontology/disaster/SnowAvalanche");
        map.put("debris avalanche","http://corp.dbpedia.org/ontology/disaster/DebrisAvalanche");
        map.put("flood","http://corp.dbpedia.org/ontology/disaster/Flood");
        map.put("flooding","http://corp.dbpedia.org/ontology/disaster/Flooding");
        map.put("flash flood","http://corp.dbpedia.org/ontology/disaster/FlashFlood");
        map.put("dam collapse","http://corp.dbpedia.org/ontology/disaster/DamCollapse");
        map.put("extreme temperatures","http://corp.dbpedia.org/ontology/disaster/ExtremeTemperatures");
        map.put("heat wave","http://corp.dbpedia.org/ontology/disaster/HeatWave");
        map.put("cold wave","http://corp.dbpedia.org/ontology/disaster/ColdWave");
        map.put("extreme cold","http://corp.dbpedia.org/ontology/disaster/ExtremeCold");
        map.put("extreme winter condition","http://corp.dbpedia.org/ontology/disaster/ExtremeWinterCondition");
        map.put("snowstorm","http://corp.dbpedia.org/ontology/disaster/Snowstorm");
        map.put("winter storm","http://corp.dbpedia.org/ontology/disaster/WinterStorm");
        map.put("hail storm","http://corp.dbpedia.org/ontology/disaster/HailStorm");
        map.put("tornado","http://corp.dbpedia.org/ontology/disaster/Tornado");
        map.put("blizzard","http://corp.dbpedia.org/ontology/disaster/Blizzard");
        map.put("ice storm","http://corp.dbpedia.org/ontology/disaster/IceStorm");
        map.put("heavy snowfall","http://corp.dbpedia.org/ontology/disaster/HeavySnowfall");
        map.put("sandstorm","http://corp.dbpedia.org/ontology/disaster/Sandstorm");
        map.put("dust storm","http://corp.dbpedia.org/ontology/disaster/DustStorm");
        map.put("drought","http://corp.dbpedia.org/ontology/disaster/Drought");
        map.put("wildfire","http://corp.dbpedia.org/ontology/disaster/Wildfire");
        map.put("forest fire","http://corp.dbpedia.org/ontology/disaster/ForestFire");
        map.put("grass fire","http://corp.dbpedia.org/ontology/disaster/GrassFire");
        map.put("scrub fire","http://corp.dbpedia.org/ontology/disaster/ScrubFire");
        map.put("land fire","http://corp.dbpedia.org/ontology/disaster/LandFire");
        map.put("bushfire","http://corp.dbpedia.org/ontology/disaster/Bushfire");
        map.put("oil fire","http://corp.dbpedia.org/ontology/disaster/OilFire");
        map.put("cyclone","http://corp.dbpedia.org/ontology/disaster/Cyclone");
        map.put("storm","http://corp.dbpedia.org/ontology/disaster/Storm");
        map.put("tropical storm","http://corp.dbpedia.org/ontology/disaster/TropicalStorm");
        map.put("tropical cyclone","http://corp.dbpedia.org/ontology/disaster/TropicalCyclone");
        map.put("typhoon","http://corp.dbpedia.org/ontology/disaster/Typhoon");
        map.put("hurricane","http://corp.dbpedia.org/ontology/disaster/Hurricane");
        map.put("thunderstorm","http://corp.dbpedia.org/ontology/disaster/Thunderstorm");
        map.put("wave surges","http://corp.dbpedia.org/ontology/disaster/WaveSurges");
        map.put("disease epidemic","http://corp.dbpedia.org/ontology/disaster/DiseaseEpidemic");
        map.put("epidemy","http://corp.dbpedia.org/ontology/disaster/Epidemy");
        map.put("epidemic","http://corp.dbpedia.org/ontology/disaster/Epidemic");
        map.put("insect plague","http://corp.dbpedia.org/ontology/disaster/InsectPlague");
        map.put("insect infestation","http://corp.dbpedia.org/ontology/disaster/InsectInfestation");
        map.put("animal plague","http://corp.dbpedia.org/ontology/disaster/AnimalPlague");
        map.put("plague","http://corp.dbpedia.org/ontology/disaster/Plague");
        map.put("pandemy","http://corp.dbpedia.org/ontology/disaster/Pandemy");
        map.put("meteorite impact","http://corp.dbpedia.org/ontology/disaster/MeteoriteImpact");
        map.put("armed conflict","http://corp.dbpedia.org/ontology/disaster/ArmedConflict");
        map.put("terrorist attack","http://corp.dbpedia.org/ontology/disaster/TerroristAttack");
        map.put("famine","http://corp.dbpedia.org/ontology/disaster/Famine");
        map.put("displaced population","http://corp.dbpedia.org/ontology/disaster/DisplacedPopulation");
        map.put("industrial accident","http://corp.dbpedia.org/ontology/disaster/IndustrialAccident");
        map.put("nuclear accident","http://corp.dbpedia.org/ontology/disaster/NuclearAccident");
        map.put("nuclear blast","http://corp.dbpedia.org/ontology/disaster/NuclearBlast");
        map.put("nuclear explosion","http://corp.dbpedia.org/ontology/disaster/NuclearExplosion");
        map.put("radiation","http://corp.dbpedia.org/ontology/disaster/Radiation");
        map.put("explosion","http://corp.dbpedia.org/ontology/disaster/Explosion");
        map.put("chemical explosion","http://corp.dbpedia.org/ontology/disaster/ChemicalExplosion");
        map.put("chemical spill","http://corp.dbpedia.org/ontology/disaster/ChemicalSpill");
        map.put("mine explosion","http://corp.dbpedia.org/ontology/disaster/MineExplosion");
        map.put("acid rain","http://corp.dbpedia.org/ontology/disaster/AcidRain");
        map.put("chemical pollution","http://corp.dbpedia.org/ontology/disaster/ChemicalPollution");
        map.put("atmosphere pollution","http://corp.dbpedia.org/ontology/disaster/AtmospherePollution");
        map.put("transport accident","http://corp.dbpedia.org/ontology/disaster/TransportAccident");
        map.put("train collision","http://corp.dbpedia.org/ontology/disaster/TrainCollision");
        map.put("ferry accident","http://corp.dbpedia.org/ontology/disaster/FerryAccident");
        map.put("oil pipeline explosion","http://corp.dbpedia.org/ontology/disaster/OilPipelineExplosion");
        map.put("environmental degradation","http://corp.dbpedia.org/ontology/disaster/EnvironmentalDegradation");
        map.put("groundwater contamination","http://corp.dbpedia.org/ontology/disaster/GroundwaterContamination");
        map.put("oil spill","http://corp.dbpedia.org/ontology/disaster/OilSpill");
        map.put("humanitarian crisis","http://corp.dbpedia.org/ontology/disaster/HumanitarianCrisis");
        map.put("disease outbreak","http://corp.dbpedia.org/ontology/disaster/DiseaseOutbreak");
        map.put("environmental disaster","http://corp.dbpedia.org/ontology/disaster/EnvironmentalDisaster");
        map.put("dioxin pollution","http://corp.dbpedia.org/ontology/disaster/DioxinPollution");
        map.put("gas leak","http://corp.dbpedia.org/ontology/disaster/GasLeak");
        map.put("man-made disaster","http://corp.dbpedia.org/ontology/disaster/ManMadeDisaster");
        map.put("natural disaster","http://corp.dbpedia.org/ontology/disaster/NaturalDisaster");
        map.put("biological disaster","http://corp.dbpedia.org/ontology/disaster/BiologicalDisaster");
        map.put("air crash","http://corp.dbpedia.org/ontology/disaster/AirCrash");
        map.put("airplane crash","http://corp.dbpedia.org/ontology/disaster/AirplaneCrash");
        mappings= Collections.unmodifiableMap(map);
    }

}
