package aksw.org.sdw.importer.avro.annotations.maps;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class Trigger {


    public static final Map<String, String> mappings;
    static {
        Map<String, String> map = new HashMap<String, String>();
        map.put("accounting adjustments","http://corp.dbpedia.org/ontology/event-trigger/AccountingAdjustments");
        map.put("accounting change","http://corp.dbpedia.org/ontology/event-trigger/AccountingChange");
        map.put("accounting review","http://corp.dbpedia.org/ontology/event-trigger/AccountingReview");
        map.put("affirm rating","http://corp.dbpedia.org/ontology/event-trigger/AffirmRating");
        map.put("allegations of false accounting","http://corp.dbpedia.org/ontology/event-trigger/AllegationsOfFalseAccounting");
        map.put("analyst recommendation","http://corp.dbpedia.org/ontology/event-trigger/AnalystRecommendation");
        map.put("analysts mean recommendation","http://corp.dbpedia.org/ontology/event-trigger/AnalystsMeanRecommendation");
        map.put("bankruptcy","http://corp.dbpedia.org/ontology/event-trigger/Bankruptcy");
        map.put("bankrupt","http://corp.dbpedia.org/ontology/event-trigger/Bankrupt");
        map.put("billion in revenue","http://corp.dbpedia.org/ontology/event-trigger/BillionInRevenue");
        map.put("billion in earnings","http://corp.dbpedia.org/ontology/event-trigger/BillionInEarnings");
        map.put("billion in profit","http://corp.dbpedia.org/ontology/event-trigger/BillionInProfit");
        map.put("billion in net earnings","http://corp.dbpedia.org/ontology/event-trigger/BillionInNetEarnings");
        map.put("billion in net profit","http://corp.dbpedia.org/ontology/event-trigger/BillionInNetProfit");
        map.put("billion in net revenue","http://corp.dbpedia.org/ontology/event-trigger/BillionInNetRevenue");
        map.put("bonus issue","http://corp.dbpedia.org/ontology/event-trigger/BonusIssue");
        map.put("bonus issue plan","http://corp.dbpedia.org/ontology/event-trigger/BonusIssuePlan");
        map.put("bonus share","http://corp.dbpedia.org/ontology/event-trigger/BonusShare");
        map.put("bonus share issue","http://corp.dbpedia.org/ontology/event-trigger/BonusShareIssue");
        map.put("bonus shares","http://corp.dbpedia.org/ontology/event-trigger/BonusShares");
        map.put("buyback plan","http://corp.dbpedia.org/ontology/event-trigger/BuybackPlan");
        map.put("buy back share","http://corp.dbpedia.org/ontology/event-trigger/BuyBackShare");
        map.put("buy back stock","http://corp.dbpedia.org/ontology/event-trigger/BuyBackStock");
        map.put("buy range","http://corp.dbpedia.org/ontology/event-trigger/BuyRange");
        map.put("buy rating","http://corp.dbpedia.org/ontology/event-trigger/BuyRating");
        map.put("capital return program","http://corp.dbpedia.org/ontology/event-trigger/CapitalReturnProgram");
        map.put("cash dividend","http://corp.dbpedia.org/ontology/event-trigger/CashDividend");
        map.put("cash flow crisis","http://corp.dbpedia.org/ontology/event-trigger/CashFlowCrisis");
        map.put("cash infusion","http://corp.dbpedia.org/ontology/event-trigger/CashInfusion");
        map.put("chapter 11","http://corp.dbpedia.org/ontology/event-trigger/Chapter11");
        map.put("Chapter 11","http://corp.dbpedia.org/ontology/event-trigger/Chapter11");
        map.put("commit money","http://corp.dbpedia.org/ontology/event-trigger/CommitMoney");
        map.put("consolidated revenue","http://corp.dbpedia.org/ontology/event-trigger/ConsolidatedRevenue");
        map.put("consolidated revenues","http://corp.dbpedia.org/ontology/event-trigger/ConsolidatedRevenues");
        map.put("credit facility","http://corp.dbpedia.org/ontology/event-trigger/CreditFacility");
        map.put("credit problems","http://corp.dbpedia.org/ontology/event-trigger/CreditProblems");
        map.put("credit rating downgrade","http://corp.dbpedia.org/ontology/event-trigger/CreditRatingDowngrade");
        map.put("credit rating upgrade","http://corp.dbpedia.org/ontology/event-trigger/CreditRatingUpgrade");
        map.put("credit rating","http://corp.dbpedia.org/ontology/event-trigger/CreditRating");
        map.put("cut a rating","http://corp.dbpedia.org/ontology/event-trigger/CutARating");
        map.put("debt financing","http://corp.dbpedia.org/ontology/event-trigger/DebtFinancing");
        map.put("debt fund","http://corp.dbpedia.org/ontology/event-trigger/DebtFund");
        map.put("debt sale","http://corp.dbpedia.org/ontology/event-trigger/DebtSale");
        map.put("delayed filing","http://corp.dbpedia.org/ontology/event-trigger/DelayedFiling");
        map.put("delist","http://corp.dbpedia.org/ontology/event-trigger/Delist");
        map.put("delisting agreement","http://corp.dbpedia.org/ontology/event-trigger/DelistingAgreement");
        map.put("delisting purchase offer","http://corp.dbpedia.org/ontology/event-trigger/DelistingPurchaseOffer");
        map.put("dividend","http://corp.dbpedia.org/ontology/event-trigger/Dividend");
        map.put("dividend payment","http://corp.dbpedia.org/ontology/event-trigger/DividendPayment");
        map.put("dividend payout","http://corp.dbpedia.org/ontology/event-trigger/DividendPayout");
        map.put("dividend payouts","http://corp.dbpedia.org/ontology/event-trigger/DividendPayouts");
        map.put("downgrade rating","http://corp.dbpedia.org/ontology/event-trigger/DowngradeRating");
        map.put("debut fund","http://corp.dbpedia.org/ontology/event-trigger/DebutFund");
        map.put("decline in earnings","http://corp.dbpedia.org/ontology/event-trigger/DeclineInEarnings");
        map.put("decline in revenue","http://corp.dbpedia.org/ontology/event-trigger/DeclineInRevenue");
        map.put("decline in profit","http://corp.dbpedia.org/ontology/event-trigger/DeclineInProfit");
        map.put("decline in net profit","http://corp.dbpedia.org/ontology/event-trigger/DeclineInNetProfit");
        map.put("decrease in revenue","http://corp.dbpedia.org/ontology/event-trigger/DecreaseInRevenue");
        map.put("decrease in earnings","http://corp.dbpedia.org/ontology/event-trigger/DecreaseInEarnings");
        map.put("decrease in profit","http://corp.dbpedia.org/ontology/event-trigger/DecreaseInProfit");
        map.put("decrease in net profit","http://corp.dbpedia.org/ontology/event-trigger/DecreaseInNetProfit");
        map.put("earnings","http://corp.dbpedia.org/ontology/event-trigger/Earnings");
        map.put("earnings announcement","http://corp.dbpedia.org/ontology/event-trigger/EarningsAnnouncement");
        map.put("earnings decline","http://corp.dbpedia.org/ontology/event-trigger/EarningsDecline");
        map.put("earnings forecast","http://corp.dbpedia.org/ontology/event-trigger/EarningsForecast");
        map.put("earnings decline","http://corp.dbpedia.org/ontology/event-trigger/EarningsDecline");
        map.put("earnings drop","http://corp.dbpedia.org/ontology/event-trigger/EarningsDrop");
        map.put("earnings growth","http://corp.dbpedia.org/ontology/event-trigger/EarningsGrowth");
        map.put("earnings loss","http://corp.dbpedia.org/ontology/event-trigger/EarningsLoss");
        map.put("earnings per share","http://corp.dbpedia.org/ontology/event-trigger/EarningsPerShare");
        map.put("earnings report","http://corp.dbpedia.org/ontology/event-trigger/EarningsReport");
        map.put("earnings results","http://corp.dbpedia.org/ontology/event-trigger/EarningsResults");
        map.put("earnings were down","http://corp.dbpedia.org/ontology/event-trigger/EarningsWereDown");
        map.put("earnings were up","http://corp.dbpedia.org/ontology/event-trigger/EarningsWereUp");
        map.put("ebitda","http://corp.dbpedia.org/ontology/event-trigger/Ebitda");
        map.put("ebit","http://corp.dbpedia.org/ontology/event-trigger/Ebit");
        map.put("eps","http://corp.dbpedia.org/ontology/event-trigger/Eps");
        map.put("equity financing","http://corp.dbpedia.org/ontology/event-trigger/EquityFinancing");
        map.put("excessive overheads","http://corp.dbpedia.org/ontology/event-trigger/ExcessiveOverheads");
        map.put("expected profit","http://corp.dbpedia.org/ontology/event-trigger/ExpectedProfit");
        map.put("expect income boost","http://corp.dbpedia.org/ontology/event-trigger/ExpectIncomeBoost");
        map.put("expect profit","http://corp.dbpedia.org/ontology/event-trigger/ExpectProfit");
        map.put("expects loss","http://corp.dbpedia.org/ontology/event-trigger/ExpectsLoss");
        map.put("expects revenue","http://corp.dbpedia.org/ontology/event-trigger/ExpectsRevenue");
        map.put("extra revenue","http://corp.dbpedia.org/ontology/event-trigger/ExtraRevenue");
        map.put("fail to file on time","http://corp.dbpedia.org/ontology/event-trigger/FailToFileOnTime");
        map.put("federal investigators","http://corp.dbpedia.org/ontology/event-trigger/FederalInvestigators");
        map.put("ffo","http://corp.dbpedia.org/ontology/event-trigger/Ffo");
        map.put("file on time (neg)","http://corp.dbpedia.org/ontology/event-trigger/FileOnTime(Neg)");
        map.put("financial mismanagement","http://corp.dbpedia.org/ontology/event-trigger/FinancialMismanagement");
        map.put("financial results","http://corp.dbpedia.org/ontology/event-trigger/FinancialResults");
        map.put("financial statement","http://corp.dbpedia.org/ontology/event-trigger/FinancialStatement");
        map.put("financing deal","http://corp.dbpedia.org/ontology/event-trigger/FinancingDeal");
        map.put("fiscal problems","http://corp.dbpedia.org/ontology/event-trigger/FiscalProblems");
        map.put("forecast a loss","http://corp.dbpedia.org/ontology/event-trigger/ForecastALoss");
        map.put("forecast a rise","http://corp.dbpedia.org/ontology/event-trigger/ForecastARise");
        map.put("fraud office prosecution","http://corp.dbpedia.org/ontology/event-trigger/FraudOfficeProsecution");
        map.put("growth in revenue","http://corp.dbpedia.org/ontology/event-trigger/GrowthInRevenue");
        map.put("growth in earnings","http://corp.dbpedia.org/ontology/event-trigger/GrowthInEarnings");
        map.put("growth in net profit","http://corp.dbpedia.org/ontology/event-trigger/GrowthInNetProfit");
        map.put("growth in profit","http://corp.dbpedia.org/ontology/event-trigger/GrowthInProfit");
        map.put("higher revenues","http://corp.dbpedia.org/ontology/event-trigger/HigherRevenues");
        map.put("higher earnings","http://corp.dbpedia.org/ontology/event-trigger/HigherEarnings");
        map.put("higher profits","http://corp.dbpedia.org/ontology/event-trigger/HigherProfits");
        map.put("higher net profit","http://corp.dbpedia.org/ontology/event-trigger/HigherNetProfit");
        map.put("hold rating","http://corp.dbpedia.org/ontology/event-trigger/HoldRating");
        map.put("increased revenues","http://corp.dbpedia.org/ontology/event-trigger/IncreasedRevenues");
        map.put("increased earnings","http://corp.dbpedia.org/ontology/event-trigger/IncreasedEarnings");
        map.put("increased profits","http://corp.dbpedia.org/ontology/event-trigger/IncreasedProfits");
        map.put("increased net profit","http://corp.dbpedia.org/ontology/event-trigger/IncreasedNetProfit");
        map.put("initial public offering","http://corp.dbpedia.org/ontology/event-trigger/InitialPublicOffering");
        map.put("initial stock offering","http://corp.dbpedia.org/ontology/event-trigger/InitialStockOffering");
        map.put("insolvency","http://corp.dbpedia.org/ontology/event-trigger/Insolvency");
        map.put("insolvent","http://corp.dbpedia.org/ontology/event-trigger/Insolvent");
        map.put("IPO","http://corp.dbpedia.org/ontology/event-trigger/Ipo");
        map.put("ipo","http://corp.dbpedia.org/ontology/event-trigger/Ipo");
        map.put("lack of capital","http://corp.dbpedia.org/ontology/event-trigger/LackOfCapital");
        map.put("lack of funds","http://corp.dbpedia.org/ontology/event-trigger/LackOfFunds");
        map.put("late filing","http://corp.dbpedia.org/ontology/event-trigger/LateFiling");
        map.put("launched an investigation","http://corp.dbpedia.org/ontology/event-trigger/LaunchedAnInvestigation");
        map.put("launch insolvency","http://corp.dbpedia.org/ontology/event-trigger/LaunchInsolvency");
        map.put("lender","http://corp.dbpedia.org/ontology/event-trigger/Lender");
        map.put("less revenue","http://corp.dbpedia.org/ontology/event-trigger/LessRevenue");
        map.put("liquidation","http://corp.dbpedia.org/ontology/event-trigger/Liquidation");
        map.put("liquidity problems","http://corp.dbpedia.org/ontology/event-trigger/LiquidityProblems");
        map.put("loss of business","http://corp.dbpedia.org/ontology/event-trigger/LossOfBusiness");
        map.put("loss of market","http://corp.dbpedia.org/ontology/event-trigger/LossOfMarket");
        map.put("lower revenues","http://corp.dbpedia.org/ontology/event-trigger/LowerRevenues");
        map.put("lower earnings","http://corp.dbpedia.org/ontology/event-trigger/LowerEarnings");
        map.put("lower profits","http://corp.dbpedia.org/ontology/event-trigger/LowerProfits");
        map.put("lower net profit","http://corp.dbpedia.org/ontology/event-trigger/LowerNetProfit");
        map.put("management failure","http://corp.dbpedia.org/ontology/event-trigger/ManagementFailure");
        map.put("million in revenue","http://corp.dbpedia.org/ontology/event-trigger/MillionInRevenue");
        map.put("million in earnings","http://corp.dbpedia.org/ontology/event-trigger/MillionInEarnings");
        map.put("million in net profit","http://corp.dbpedia.org/ontology/event-trigger/MillionInNetProfit");
        map.put("million in net revenue","http://corp.dbpedia.org/ontology/event-trigger/MillionInNetRevenue");
        map.put("million in net earnings","http://corp.dbpedia.org/ontology/event-trigger/MillionInNetEarnings");
        map.put("million in profit","http://corp.dbpedia.org/ontology/event-trigger/MillionInProfit");
        map.put("move to bourse","http://corp.dbpedia.org/ontology/event-trigger/MoveToBourse");
        map.put("net asset value per share","http://corp.dbpedia.org/ontology/event-trigger/NetAssetValuePerShare");
        map.put("net interest income","http://corp.dbpedia.org/ontology/event-trigger/NetInterestIncome");
        map.put("net earnings","http://corp.dbpedia.org/ontology/event-trigger/NetEarnings");
        map.put("net revenue","http://corp.dbpedia.org/ontology/event-trigger/NetRevenue");
        map.put("net profit","http://corp.dbpedia.org/ontology/event-trigger/NetProfit");
        map.put("neutral rating","http://corp.dbpedia.org/ontology/event-trigger/NeutralRating");
        map.put("nii","http://corp.dbpedia.org/ontology/event-trigger/Nii");
        map.put("net profit growth","http://corp.dbpedia.org/ontology/event-trigger/NetProfitGrowth");
        map.put("net profit loss","http://corp.dbpedia.org/ontology/event-trigger/NetProfitLoss");
        map.put("net profit was down","http://corp.dbpedia.org/ontology/event-trigger/NetProfitWasDown");
        map.put("net profit was up","http://corp.dbpedia.org/ontology/event-trigger/NetProfitWasUp");
        map.put("non-interest income","http://corp.dbpedia.org/ontology/event-trigger/Non-InterestIncome");
        map.put("notice of intent","http://corp.dbpedia.org/ontology/event-trigger/NoticeOfIntent");
        map.put("notification of late filing","http://corp.dbpedia.org/ontology/event-trigger/NotificationOfLateFiling");
        map.put("one-for-one bonus issue","http://corp.dbpedia.org/ontology/event-trigger/One-For-OneBonusIssue");
        map.put("overextension of credit","http://corp.dbpedia.org/ontology/event-trigger/OverextensionOfCredit");
        map.put("overstate profits","http://corp.dbpedia.org/ontology/event-trigger/OverstateProfits");
        map.put("payout","http://corp.dbpedia.org/ontology/event-trigger/Payout");
        map.put("posts loss","http://corp.dbpedia.org/ontology/event-trigger/PostsLoss");
        map.put("profit decline","http://corp.dbpedia.org/ontology/event-trigger/ProfitDecline");
        map.put("profit drop","http://corp.dbpedia.org/ontology/event-trigger/ProfitDrop");
        map.put("profit growth","http://corp.dbpedia.org/ontology/event-trigger/ProfitGrowth");
        map.put("profit loss","http://corp.dbpedia.org/ontology/event-trigger/ProfitLoss");
        map.put("profit was down","http://corp.dbpedia.org/ontology/event-trigger/ProfitWasDown");
        map.put("profit was up","http://corp.dbpedia.org/ontology/event-trigger/ProfitWasUp");
        map.put("prosecution","http://corp.dbpedia.org/ontology/event-trigger/Prosecution");
        map.put("public offering","http://corp.dbpedia.org/ontology/event-trigger/PublicOffering");
        map.put("quarterly profit","http://corp.dbpedia.org/ontology/event-trigger/QuarterlyProfit");
        map.put("raise in equity","http://corp.dbpedia.org/ontology/event-trigger/RaiseInEquity");
        map.put("raise in financing","http://corp.dbpedia.org/ontology/event-trigger/RaiseInFinancing");
        map.put("rating agency","http://corp.dbpedia.org/ontology/event-trigger/RatingAgency");
        map.put("receivership","http://corp.dbpedia.org/ontology/event-trigger/Receivership");
        map.put("re-file","http://corp.dbpedia.org/ontology/event-trigger/Re-File");
        map.put("regulatory investigations","http://corp.dbpedia.org/ontology/event-trigger/RegulatoryInvestigations");
        map.put("report a loss","http://corp.dbpedia.org/ontology/event-trigger/ReportALoss");
        map.put("repurchase by the company","http://corp.dbpedia.org/ontology/event-trigger/RepurchaseByTheCompany");
        map.put("repurchases share","http://corp.dbpedia.org/ontology/event-trigger/RepurchasesShare");
        map.put("repurchases stock","http://corp.dbpedia.org/ontology/event-trigger/RepurchasesStock");
        map.put("restate","http://corp.dbpedia.org/ontology/event-trigger/Restate");
        map.put("revenue decline","http://corp.dbpedia.org/ontology/event-trigger/RevenueDecline");
        map.put("revenue drop","http://corp.dbpedia.org/ontology/event-trigger/RevenueDrop");
        map.put("revenue growth","http://corp.dbpedia.org/ontology/event-trigger/RevenueGrowth");
        map.put("revenue loss","http://corp.dbpedia.org/ontology/event-trigger/RevenueLoss");
        map.put("revenue was down","http://corp.dbpedia.org/ontology/event-trigger/RevenueWasDown");
        map.put("revenue was up","http://corp.dbpedia.org/ontology/event-trigger/RevenueWasUp");
        map.put("sec filing","http://corp.dbpedia.org/ontology/event-trigger/SecFiling");
        map.put("secondary market offering","http://corp.dbpedia.org/ontology/event-trigger/SecondaryMarketOffering");
        map.put("secondary offering","http://corp.dbpedia.org/ontology/event-trigger/SecondaryOffering");
        map.put("sell rating","http://corp.dbpedia.org/ontology/event-trigger/SellRating");
        map.put("share buyback","http://corp.dbpedia.org/ontology/event-trigger/ShareBuyback");
        map.put("share issuance","http://corp.dbpedia.org/ontology/event-trigger/ShareIssuance");
        map.put("share repurchase program","http://corp.dbpedia.org/ontology/event-trigger/ShareRepurchaseProgram");
        map.put("shares dividend","http://corp.dbpedia.org/ontology/event-trigger/SharesDividend");
        map.put("shares issuance","http://corp.dbpedia.org/ontology/event-trigger/SharesIssuance");
        map.put("share splits","http://corp.dbpedia.org/ontology/event-trigger/ShareSplits");
        map.put("split of stock","http://corp.dbpedia.org/ontology/event-trigger/SplitOfStock");
        map.put("split stock","http://corp.dbpedia.org/ontology/event-trigger/SplitStock");
        map.put("start insolvency procedures","http://corp.dbpedia.org/ontology/event-trigger/StartInsolvencyProcedures");
        map.put("stock buyback","http://corp.dbpedia.org/ontology/event-trigger/StockBuyback");
        map.put("stock issuance","http://corp.dbpedia.org/ontology/event-trigger/StockIssuance");
        map.put("stock repurchase program","http://corp.dbpedia.org/ontology/event-trigger/StockRepurchaseProgram");
        map.put("stock split","http://corp.dbpedia.org/ontology/event-trigger/StockSplit");
        map.put("strong buy","http://corp.dbpedia.org/ontology/event-trigger/StrongBuy");
        map.put("strong-buy rating","http://corp.dbpedia.org/ontology/event-trigger/Strong-BuyRating");
        map.put("target projections","http://corp.dbpedia.org/ontology/event-trigger/TargetProjections");
        map.put("tax evasion","http://corp.dbpedia.org/ontology/event-trigger/TaxEvasion");
        map.put("top pick rating","http://corp.dbpedia.org/ontology/event-trigger/TopPickRating");
        map.put("underperform","http://corp.dbpedia.org/ontology/event-trigger/Underperform");
        map.put("unsecured notes","http://corp.dbpedia.org/ontology/event-trigger/UnsecuredNotes");
        map.put("upgrade rating","http://corp.dbpedia.org/ontology/event-trigger/UpgradeRating");
        map.put("yearly profit","http://corp.dbpedia.org/ontology/event-trigger/YearlyProfit");
        mappings= Collections.unmodifiableMap(map);
    }
}
